#!/usr/bin/perl
# Searching files in a directory
use warnings;
use strict;
use Term::ANSIColor; # For Coloured Print Statements

# Author: Joseph Crisp
# Calculate Isolate Coverage in FASTA file

# Command Line Structure
# perl CalculateIsolateCoverage.pl sequences_date.fasta

# FASTA File Format:
# 218 969
# >WB8_S22_171.vcf
# GGGGGCGGCCGCCACTGCCGACCCCCAACGCCGCCCTAAGTGGCCTTCATCTGCTGTGTCCGTCTACTCCTCCCACCTGCTCCCACAGCCCAGACCCCTCCTCATCCGGGCGTTTTCGTGTGTTAGCATCTAGGGGCCCTATGGTCGCCGCGCTCCGCTAGGGGCCTGCAATCGCGCACCTCAAGAAAAGAAAAAGATCCCCGCCAACCCTATCCCTCCACAACCCGACGAAATGCCTGATGGTTGGTGCGCGCGCGGCTTTCCGCTTCCTCCTACGCGCCTTCGGAGGCGGCAGCTCCCATTGTTACGTCTACGCCCGTGGGCCGTCCCACCAACGTTCGTAAGGCCCGAGTTTGCGGATTGACCATCAGCCGCGGTGTCCCGGTCGGCGTTCGCCCCACTTGTGAGCGTGTTGCAGCTGCTGGCTCCCCGTTACAAGCGGGCCTGGCGCGCCCGGAGGCTAGTTCGGGGAGCCTTTACAACTTGGTGACTCCGCCGGCCCTAGCGTTAGCCCCTATCGTCGACGAGCAGCGGGGCGGCTTGGCCTCGTCGGGCGAGTGGCCGGCGCTAGTAAGGCGGCCGAACTCGTTGCTCACAAGGGGCGGAAACACGGCCCCCGCTAGCCGGAGGTTCCATGAGGGGCGTCCTGGGGGCCACCGACAGAGGCGGGTGAAGTTAAGGCCGGTTCGCGGGTCCGTCTTCGGAGGGCCGCGAGCGACGCNACGCGGTGTGACGGGCCGTCCGCAGTGCAGAGCGGGCTTGCTTGTAAAGGTAGGAGCAAGGCTGTCTTGGATGGAGCGCGCACGGCAGGCCGTCTGCGAAGCCACGTATACTCTGGGCCGCCCTCGGAGAAGTTCGGGGGCGTCAGGAGGTCCGAGGGGTCCGAACNGAGGTGTGCGGGCCGGGGATTCGGGTTGGGGCCTGCGGTTCCACTGCAGTCGTCCGCCCCCGATGTTGTGCGAAGGGCCC
# >WB90_S54_172.vcf
# GGGGGCGGCNGCCANTGCCGACNCCNAACGCCACCCTANGTGGCCNNCATCTNCCGTGTCCGTCTACTCCTCCCACCTGCTCACACAGCCCAGACCCCTCCTCATCCGGGCGNTTTCGTGTGTCAGCATCTAGGGGCCCTATGGTCGCCGCGCTCCGTTAGGGGCCTGCAATCGCGCACCTCAATAAAAGAAAAAGATCCCCGCCAACCCTATCCCTCCACAACCCGACGAAATGCCTGATGGTTNGTGCGCGTGCCGCTTTCCGCTTCCTCCTACGCGCCCTCNGANGCGGCAGCTCCCATTGGTACGTCTACGCCCATGGGCCNTCCCACCGACGTTCGTAAGGCCCGAGTTTGCGGATTGACCATCAGCCGCGGTGTCCCGGTCGGCNTTCGCCCCATTTGTAAGCGTGTTGCAGCTGCTAGCTCCNCTTTATAAGCGGNCNTGACGCGCCCGGAGGCTAGTTCGGGGAGCCTTTACAACTTGGTGACTCCGCCGGCCCTAGCGTTCGCCNCTATCGTCGACGAGCNGCGGGGTGGCTTGGCCTCGTCGGGCGAGTGGCCNGCGCCNGTAAGGCGGCCGAACTCGTTGCTCACAAGGGGCGGAAACACGGCCCCCGNTAGCCGGAGGTTCCATGAGGGGCGTCCTGGGGGCCACCGACAGAGGCGGGTGAAGTTAAGGCCGGTTCGCGGGTCCGTCTCCGGAGGGCCGCGAGCGACGCTACGCGGTGTGACGGGCCGTCCGCAGTGCAGANCGGGCTTGCTTGTAAAGGTAGGAGCAAGGCTGTCTTGGATGGAGCGCGCACGGCAGGCCGTCTGCGAAGCCACGNGTACTCTGGGCCGCNCTCGGAGAAGTTCGGGGNCGTCAGGAGGTCCGAGGGGTCCGAACTNAGNNGTGCGGGCCGGGGATTCGGGTNGGGGCCTGCGGTTCCACTGCAGTCATCCGCCCCCGATGTTGTGCGAAGGGCCC
# >WB92_S71_174.vcf
# GGGGGCGNCNGCCACTGCCGACCCCCAACGCCGCCCTAAGTGNCCTTCATCTNCNGTGTCCGTCTACTCCTCCCACCTGCTCCNACAGCCCAGACCCCTCCTCATCCGGGCGTTTTCGTGTGTTAGCATCTAGGGGCCCTATGGTCGCCGCGCTCCGCTAGGGGCCTGCAATCGCGCACCTCAAGAAAAGAAAAAGATCCCTGCCAACCCTATCCCTCCACAACCCGACGAANTGCCTGATGGTTGGTGCGCGCGCGGCTTTCCGCTNCCTCCTACGCGCCTTCGGAGGCGGCAGCTCCCNTNGTTACGTCTACGCCNATGGGCCGTCTCACCANNGTTCGTANGGCCCGAGTTTGCAGATTGNCCATCAGCCGCGGTGTCCCGGTCGGCGTTCGCCCCACTTGTAAGCGTGTTGCAGCTGNTGGCTCCCCTTTACNAGCGGGCNTGGCGCGCCCGGAGGCNAGTTCGGGGAGCCTTTACAACTTGGTGACTCCGCCGGCCCTAGNGTTAGCCCCTATCGNCGACGAGCAGCGGGGCGGCTTGGCCTCGTCGGGCGAGTGGCCGGCGCTAGTAAGGCGGCCGAACTCGTTGCNCCCAAGGGGCGGAAACACGGCCCCCGNTAGCCGGAGGTTCCANGAGGGGCGTCCTGGGGGCCACCGACAGAGGCGGGTGAAGTTAAGGCCGGTTCGCGGGTCCGTCTTCGGAGGGCCGCNAGCGACGCTACNCGGTGTGACGGGCCGTNCGCAGTGCAGAGCGGGCTTGCTTGTAAAGGTANGANCAAGGCTGTNTTGGATGGAGCGCGCACGGCAGGCCGTCTGCGAAGCCACGTATACTCTGGGCCGCCCTCGGAGAAGTTCGGGGGCGTCAGGAGGTCCGAGGGGTCCGAACTGAGGTGTGCGGGNCGGGGATTCGGGTTGGGGCCTGCGGTTCCACTGCAGTCGNCCGCCCCCGATGTTGTGCGAAGGGCCC
# >WB93_S8_175.vcf
# GGGGGCGGCCGCCACTGCCGACCCCCAACGCCGCCCTAAGTGGCCTTCATCTGCTGTGTCCGTCTACTCCTCCCACCTGCTCCCACAGCCCAGACCCCTCCTCATCCGGNCGTTTTCGTGTGTTAGCATCTAGGNGCCCTATGGTCGCCGCGCTCCGCTAGGGGCCTGCAATCGCGCACCTNAAGAAAAGAAAAAGATCCCTGCCAACCCTATCCCTCCACAACCCGACGAAATGCCTGATGGTTGGTGCGCGCGCGGCTTTCCGCTTCCTNCTACGCGCCTTCGGAGGCGGCAGCTCCCATTGTTACGTCNACGCCCATGGGCCGTCTCACCANCGTTCGTAAGGCCCGAGTTTGCAGATTGACCATCAGCCGCGGTGTCCCGGTCGGCGTTCGCCCCNCTTGTAAGCGTGTTGCAGCTGCTGGCTCCCCTTTACAAGCGGNCCTGGCGCGCCCGGAGGCTAGTTCGGGGAGCCTTTACAACTTGGTGACTCCGCCGGCCCTAGCGTTAGCCCCTATCGTCGACGAGCAGCGGGGCGGCTTGGCCTCGTCGGGCGAGTGGCCGGCGCTANTAAGGCGGCCGAACTCGTTGCTCCCAAGGGGCGGAAACACGGCCCCCGCTAGCCGGAGGTTCCATGAGGGGCGTCCTGGGGGCCACCGACAGAGGCGGGTGAAGTTAAGGCCGGTTCGCGGGTCCGTCTNCGGAGGGCCGCGAGCGACGCTACGCGGTGTGACGGGCCGTCCGCAGTGCAGAGCGGGCTTGCTTGTAAAGGTAGGAGCAAGGCTGTCTTGGATGGAGCGCGCACGNCAGGCCGTCTGCGAAGCCACGNATACTCTGGGCCGCCCTCGGAGAAGTTCGGGGGCGTCAGGAGGTCNGAGGGGTCCGAACTGAGGTGTGCGGGCCGGGGATTCGGGTTGGGGCCTGCGGTTCCACTGCAGTCGTCCGCCCCCGATGTTGTGCGAAGGGCCC
# ...

# Get first variable from command line
my $firstArg = shift @ARGV;

# Print help information if requested
if($firstArg eq "-help" || $firstArg eq "" || $firstArg eq "-h" || $firstArg eq "help"){
	print color("green"), "Perl Script calculate site coverage in FASTA.\n\nCommand Line Structure:\n", color("reset");
	print "\tperl CalculateIsolateCoverage.pl sequences_date.fasta\n";
	print "\t\tsequences_date.fasta\tPath to FASTA file, file should have date as last delimited part of name\n";

	exit 0;	
}

# Open in the Sample FASTA File
my $fastaFile = $firstArg; 
open FASTA, $fastaFile or die "Couldn't open $fastaFile:$!";

# Create a file to store the coverage of each isolate
my $outputTable = "IsolateVariantPositionCoverage_" . (split /\./, (split /_/, $fastaFile)[-1])[0] . ".txt";
open COVERAGE, ">$outputTable" or die "Couldn't open $outputTable:$!";
print COVERAGE "Isolate\tVariantPositionCoverage\n";

# Check the input settings
print "Input settings:\n";
print "\tFASTA file: $fastaFile\n";
print "\nThe following output files will be produced:\n";
print "\t$outputTable\tTable reporting the proportion of sites with an allele present\n\n";

# Create variables to store the isolateIDs and sequence
my $name;
my $sequence;
my @names;
my @sequences;
my $index = -1;
my @nucleotides;
my $prop;

# Create the necessary variables for parsing the FASTA file
my $line;
my @cols;
my $lineNo = 0;

# Begin reading the FASTA file
while(<FASTA>){
	$lineNo++;
	$line = $_;
	chomp($line);
	
	# Skip the first line
	next if $lineNo == 1;
	
	# Have we found a new isolate?
	if($line =~ /^>/){
		
		# Print out the information for the previous isolate if it has a high enough quality
		if($lineNo != 2){
			
			@nucleotides = split //, $sequence;
			$prop = 0;
			
			for(my $i = 0; $i < scalar(@nucleotides); $i++){
				$prop++ if $nucleotides[$i] ne "N";
			}
			$prop = $prop / scalar(@nucleotides);
			
			print COVERAGE "$name\t$prop\n";	
		}
		
		# Get the isolate name
		$name = substr($line, 1);
		
		# Reset the sequence
		$sequence = "";
	}else{
		$sequence = $sequence . "" . $line;
	}
}

# Deal with the last sequence
@nucleotides = split //, $sequence;
$prop = 0;

for(my $i = 0; $i < scalar(@nucleotides); $i++){
	$prop++ if $nucleotides[$i] ne "N";
}
$prop = $prop / scalar(@nucleotides);

print COVERAGE "$name\t$prop\n";

# Close the input and output files
close(FASTA);
